server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adressbook_app?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update